### ISSUE TITLE
'Tabs and Spaces' example does not actually include tabs

### ISSUE THREAD

**Issue by adamobeng** [swcarpentry/python-novice-inflammation#221] opened 2016-01-27 19:48 UTC
The "Tabs and Spaces" callout in lesson 7 includes a code example where supposedly "the first two lines are using a tab for indentation, while the third line uses four spaces". In fact, all three lines use spaces for indentation.

Someone copying this example would not be able to reproduce the error.

I'm opening an issue rather than just fixing it, because:
1. this might be a deliberate decision (the markdown file also has spaces, so this is not just a conversion problem)?
2. fixing it is non-trivial, given that pandoc converts tabs to spaces by default (the '--preserve-tabs' option would have to be added to the pandoc call in the Makefile).

**Comment by gvwilson** [comment] 2016-07-31 23:56
Yeah, this is hard to fix given that we're using Markdown...

**Comment by yeemey** [comment] 2018-04-20 17:48
I typed out the code example as described in Jupyter, and cannot reproduce the ```TabError```. Trying this out in the command line gives me an ```IndentationError``` instead. 

Either we revise the example to reproduce the error (I tried some random combinations of tabs/spaces, and couldn't get it), or remove it and just note that it's not good practice to mix tabs and spaces?

From the [Python 3 docs](https://docs.python.org/3/reference/lexical_analysis.html#indentation):
> Tabs are replaced (from left to right) by one to eight spaces such that the total number of characters up to and including the replacement is a multiple of eight (this is intended to be the same rule as used by Unix).
> ...
> Indentation is rejected as inconsistent if a source file mixes tabs and spaces in a way that makes the meaning dependent on the worth of a tab in spaces; a TabError is raised in that case.

**Comment by maxim-belkin** [comment] 2018-04-20 17:54
Hey @yeemey!
Could you please be more specific as to which line in which file you're talking about. Thank you!

**Comment by yeemey** [comment] 2018-04-20 18:03
Hi @maxim-belkin,
It's the [episode 7 lesson on errors and exceptions](http://swcarpentry.github.io/python-novice-inflammation/07-errors/).

It's ~line 182 in my forked repo with 07-errors.md.

**Comment by tbekolay** [comment] 2018-04-20 18:04
> I typed out the code example as described in Jupyter, and cannot reproduce the TabError

You have to copy/paste the example, not type it out manually.

**Comment by tbekolay** [comment] 2018-04-20 18:05
And actually this issue should be fixed now as I did change the HTML to have explicit tabs in there; I just copy/pasted and it worked for me.

**Closed by tbekolay** 2018-04-20 18:05 UTC
