### ISSUE TITLE
Tuples referenced but not included in lesson

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/python-novice-inflammation#262] opened 2016-04-06 17:48 UTC
From an email I received:

Dear Software Carpentry,

Thank you for doing this work. I refer all scientists I know who express interest in becoming better programmers to your website and lessons.

I have one small bug report. I was reading your Python lesson on conditionals. One of the learning objectives is explaining the difference between tuples and lists, but tuples are not mentioned again in the lesson.
http://swcarpentry.github.io/python-novice-inflammation/05-cond.html

Also tuples and ipythonblocks library are mentioned in the reference material, but are not present in the lesson.
http://swcarpentry.github.io/python-novice-inflammation/reference.html

Thanks again for making this service available.

**Comment by QuLogic** [comment] 2016-05-11 06:44
This is (mostly) a dupe of #96.

**Closed** 2016-06-08 06:48 UTC
